/**
 * Dữ liệu bài tập "Thể bị động".
 *
 * `id` là một slug lấy từ chính câu chủ động — ổn định, đọc được khi soi
 * localStorage, và không cần đánh số lại khi chèn thêm câu vào giữa (đánh số thì
 * chèn một câu là mọi ★ phía sau lệch hết).
 *
 * Mỗi câu phải TỰ ĐỦ: cặp chủ động/bị động đúng ngữ pháp và cùng nghĩa, `formulaId`
 * trỏ đúng dòng công thức, `reversible` nói thật về việc có dựng lại được câu chủ
 * động hay không. `scripts/verify-data.mjs` kiểm tra lại các ràng buộc này.
 */

import type { LocalizedText } from '../models/lesson.model';
import type { PassiveFormula, PassiveSentence } from './exercise.model';

/**
 * Bảng công thức bị động theo thì.
 *
 * Ba thì hoàn thành tiếp diễn (hiện tại/quá khứ/tương lai) KHÔNG có mặt ở đây, và
 * đó không phải thiếu sót: dạng bị động của chúng ("has been being done") về lý
 * thuyết dựng được nhưng thực tế không ai dùng, và TOEIC không hỏi. Đưa vào chỉ
 * làm người học tưởng mình phải nhớ thêm ba công thức nữa.
 */
export const PASSIVE_FORMULAS: readonly PassiveFormula[] = [
  {
    id: 'present-simple',
    name: { vi: 'Hiện tại đơn', en: 'Present Simple' },
    active: 'S + V(s/es) + O',
    passive: 'S + am/is/are + V3 (+ by O)',
    example: 'The staff clean the office. → The office is cleaned by the staff.',
  },
  {
    id: 'present-continuous',
    name: { vi: 'Hiện tại tiếp diễn', en: 'Present Continuous' },
    active: 'S + am/is/are + V-ing + O',
    passive: 'S + am/is/are + being + V3 (+ by O)',
    example: 'They are painting the lobby. → The lobby is being painted.',
  },
  {
    id: 'present-perfect',
    name: { vi: 'Hiện tại hoàn thành', en: 'Present Perfect' },
    active: 'S + have/has + V3 + O',
    passive: 'S + have/has + been + V3 (+ by O)',
    example: 'She has sent the invoice. → The invoice has been sent.',
  },
  {
    id: 'past-simple',
    name: { vi: 'Quá khứ đơn', en: 'Past Simple' },
    active: 'S + V2 + O',
    passive: 'S + was/were + V3 (+ by O)',
    example: 'The manager signed the contract. → The contract was signed by the manager.',
  },
  {
    id: 'past-continuous',
    name: { vi: 'Quá khứ tiếp diễn', en: 'Past Continuous' },
    active: 'S + was/were + V-ing + O',
    passive: 'S + was/were + being + V3 (+ by O)',
    example: 'They were inspecting the machines. → The machines were being inspected.',
  },
  {
    id: 'past-perfect',
    name: { vi: 'Quá khứ hoàn thành', en: 'Past Perfect' },
    active: 'S + had + V3 + O',
    passive: 'S + had + been + V3 (+ by O)',
    example: 'We had booked the room. → The room had been booked.',
  },
  {
    id: 'future-simple',
    name: { vi: 'Tương lai đơn', en: 'Future Simple' },
    active: 'S + will + V + O',
    passive: 'S + will + be + V3 (+ by O)',
    example: 'The team will announce the results. → The results will be announced.',
  },
  {
    id: 'future-perfect',
    name: { vi: 'Tương lai hoàn thành', en: 'Future Perfect' },
    active: 'S + will have + V3 + O',
    passive: 'S + will have been + V3 (+ by O)',
    example: 'They will have completed the audit. → The audit will have been completed.',
  },
  {
    id: 'be-going-to',
    name: { vi: 'Dự định (be going to)', en: 'Be going to' },
    active: 'S + am/is/are going to + V + O',
    passive: 'S + am/is/are going to be + V3 (+ by O)',
    example: 'We are going to review the budget. → The budget is going to be reviewed.',
  },
  {
    id: 'modal',
    name: { vi: 'Động từ khuyết thiếu', en: 'Modal verbs' },
    active: 'S + modal + V + O',
    passive: 'S + modal + be + V3 (+ by O)',
    example: 'You must submit the form. → The form must be submitted.',
  },
];

export function passiveFormula(id: string): PassiveFormula | null {
  return PASSIVE_FORMULAS.find((item) => item.id === id) ?? null;
}

/** Ghi chú dùng lại ở nhiều câu — khai một lần cho khỏi lệch chữ giữa các câu. */
const NOTE_TWO_OBJECTS: LocalizedText = {
  vi: 'Động từ hai tân ngữ: tân ngữ chỉ NGƯỜI thường được đưa lên làm chủ ngữ. Câu kia cũng đúng nhưng phải thêm giới từ: "A bonus was given to the employees."',
  en: 'Two-object verb: the PERSON object usually becomes the subject. The other version is also correct but needs a preposition: "A bonus was given to the employees."',
};

const NOTE_PHRASAL: LocalizedText = {
  vi: 'Giới từ dính liền với động từ, không được bỏ lại phía sau: "was put off", không phải "was put".',
  en: 'The particle travels with the verb — "was put off", never "was put".',
};

const NOTE_BY_OMITTED: LocalizedText = {
  vi: 'Chủ ngữ chủ động là "they / someone / people" — không rõ ai, nên phần "by ..." bị lược bỏ.',
  en: 'The active subject is "they / someone / people" — nobody specific, so the "by ..." phrase is dropped.',
};

export const PASSIVE_SENTENCES: readonly PassiveSentence[] = [
  // ── Hiện tại đơn ─────────────────────────────────────────────────────────
  {
    id: 'staff-clean-office',
    formulaId: 'present-simple',
    kind: 'standard',
    active: 'The staff clean the office every evening.',
    passive: 'The office is cleaned by the staff every evening.',
    vietnamese: 'Văn phòng được nhân viên dọn dẹp mỗi tối.',
    reversible: true,
    note: null,
  },
  {
    id: 'supplier-delivers-components',
    formulaId: 'present-simple',
    kind: 'standard',
    active: 'Our supplier delivers the components on Mondays.',
    passive: 'The components are delivered by our supplier on Mondays.',
    vietnamese: 'Các linh kiện được nhà cung cấp của chúng tôi giao vào thứ Hai hằng tuần.',
    reversible: true,
    note: null,
  },
  {
    id: 'security-checks-visitors',
    formulaId: 'present-simple',
    kind: 'standard',
    active: 'The security team checks all visitors at the entrance.',
    passive: 'All visitors are checked by the security team at the entrance.',
    vietnamese: 'Tất cả khách tới đều được đội an ninh kiểm tra ở cửa vào.',
    reversible: true,
    note: null,
  },
  {
    id: 'company-tests-every-batch',
    formulaId: 'present-simple',
    kind: 'standard',
    active: 'The laboratory tests every batch before shipment.',
    passive: 'Every batch is tested by the laboratory before shipment.',
    vietnamese: 'Mỗi lô hàng đều được phòng thí nghiệm kiểm nghiệm trước khi xuất đi.',
    reversible: true,
    note: null,
  },
  {
    id: 'they-hold-board-meeting',
    formulaId: 'present-simple',
    kind: 'byOmitted',
    active: 'They hold the board meeting in the main conference room.',
    passive: 'The board meeting is held in the main conference room.',
    vietnamese: 'Cuộc họp hội đồng quản trị được tổ chức tại phòng họp chính.',
    reversible: false,
    note: NOTE_BY_OMITTED,
  },
  {
    id: 'someone-waters-plants',
    formulaId: 'present-simple',
    kind: 'byOmitted',
    active: 'Someone waters the plants twice a week.',
    passive: 'The plants are watered twice a week.',
    vietnamese: 'Cây được tưới hai lần một tuần.',
    reversible: false,
    note: NOTE_BY_OMITTED,
  },

  // ── Hiện tại tiếp diễn ───────────────────────────────────────────────────
  {
    id: 'contractors-painting-lobby',
    formulaId: 'present-continuous',
    kind: 'standard',
    active: 'The contractors are painting the lobby this week.',
    passive: 'The lobby is being painted by the contractors this week.',
    vietnamese: 'Sảnh đang được các nhà thầu sơn trong tuần này.',
    reversible: true,
    note: null,
  },
  {
    id: 'it-upgrading-servers',
    formulaId: 'present-continuous',
    kind: 'standard',
    active: 'The IT department is upgrading the servers.',
    passive: 'The servers are being upgraded by the IT department.',
    vietnamese: 'Các máy chủ đang được phòng công nghệ thông tin nâng cấp.',
    reversible: true,
    note: null,
  },
  {
    id: 'designers-preparing-brochure',
    formulaId: 'present-continuous',
    kind: 'standard',
    active: 'Our designers are preparing the new brochure.',
    passive: 'The new brochure is being prepared by our designers.',
    vietnamese: 'Cuốn brochure mới đang được các nhà thiết kế của chúng tôi chuẩn bị.',
    reversible: true,
    note: null,
  },
  {
    id: 'auditors-reviewing-accounts',
    formulaId: 'present-continuous',
    kind: 'standard',
    active: 'The auditors are reviewing last year’s accounts.',
    passive: 'Last year’s accounts are being reviewed by the auditors.',
    vietnamese: 'Sổ sách năm ngoái đang được các kiểm toán viên rà soát.',
    reversible: true,
    note: null,
  },
  {
    id: 'they-processing-refund',
    formulaId: 'present-continuous',
    kind: 'byOmitted',
    active: 'They are processing your refund right now.',
    passive: 'Your refund is being processed right now.',
    vietnamese: 'Khoản hoàn tiền của bạn đang được xử lý ngay lúc này.',
    reversible: false,
    note: NOTE_BY_OMITTED,
  },

  // ── Hiện tại hoàn thành ──────────────────────────────────────────────────
  {
    id: 'accountant-sent-invoice',
    formulaId: 'present-perfect',
    kind: 'standard',
    active: 'The accountant has sent the invoice to the client.',
    passive: 'The invoice has been sent to the client by the accountant.',
    vietnamese: 'Hoá đơn đã được kế toán gửi cho khách hàng.',
    reversible: true,
    note: null,
  },
  {
    id: 'board-approved-budget',
    formulaId: 'present-perfect',
    kind: 'standard',
    active: 'The board has approved the annual budget.',
    passive: 'The annual budget has been approved by the board.',
    vietnamese: 'Ngân sách năm đã được hội đồng quản trị phê duyệt.',
    reversible: true,
    note: null,
  },
  {
    id: 'team-finished-market-research',
    formulaId: 'present-perfect',
    kind: 'standard',
    active: 'Our team has finished the market research.',
    passive: 'The market research has been finished by our team.',
    vietnamese: 'Nghiên cứu thị trường đã được nhóm chúng tôi hoàn thành.',
    reversible: true,
    note: null,
  },
  {
    id: 'hotel-upgraded-rooms',
    formulaId: 'present-perfect',
    kind: 'standard',
    active: 'The hotel has upgraded all the rooms.',
    passive: 'All the rooms have been upgraded by the hotel.',
    vietnamese: 'Toàn bộ các phòng đã được khách sạn nâng cấp.',
    reversible: true,
    note: {
      vi: 'Chủ ngữ mới là "all the rooms" (số nhiều) nên trợ động từ đổi thành have, không phải has.',
      en: 'The new subject "all the rooms" is plural, so the auxiliary becomes have, not has.',
    },
  },
  {
    id: 'they-cancelled-afternoon-session',
    formulaId: 'present-perfect',
    kind: 'byOmitted',
    active: 'They have cancelled the afternoon session.',
    passive: 'The afternoon session has been cancelled.',
    vietnamese: 'Phiên làm việc buổi chiều đã bị huỷ.',
    reversible: false,
    note: NOTE_BY_OMITTED,
  },
  {
    id: 'management-extended-deadline',
    formulaId: 'present-perfect',
    kind: 'standard',
    active: 'Management has extended the deadline.',
    passive: 'The deadline has been extended by management.',
    vietnamese: 'Hạn chót đã được ban lãnh đạo gia hạn.',
    reversible: true,
    note: null,
  },

  // ── Quá khứ đơn ──────────────────────────────────────────────────────────
  {
    id: 'manager-signed-contract',
    formulaId: 'past-simple',
    kind: 'standard',
    active: 'The manager signed the contract yesterday.',
    passive: 'The contract was signed by the manager yesterday.',
    vietnamese: 'Hợp đồng đã được giám đốc ký hôm qua.',
    reversible: true,
    note: null,
  },
  {
    id: 'local-firm-built-warehouse',
    formulaId: 'past-simple',
    kind: 'standard',
    active: 'A local firm built the warehouse in 2018.',
    passive: 'The warehouse was built by a local firm in 2018.',
    vietnamese: 'Nhà kho được một công ty địa phương xây vào năm 2018.',
    reversible: true,
    note: null,
  },
  {
    id: 'technician-repaired-copier',
    formulaId: 'past-simple',
    kind: 'standard',
    active: 'The technician repaired the copier this morning.',
    passive: 'The copier was repaired by the technician this morning.',
    vietnamese: 'Máy photocopy đã được kỹ thuật viên sửa sáng nay.',
    reversible: true,
    note: null,
  },
  {
    id: 'supplier-raised-prices',
    formulaId: 'past-simple',
    kind: 'standard',
    active: 'Our supplier raised the prices in April.',
    passive: 'The prices were raised by our supplier in April.',
    vietnamese: 'Giá đã bị nhà cung cấp của chúng tôi tăng vào tháng Tư.',
    reversible: true,
    note: null,
  },
  {
    id: 'ceo-announced-merger',
    formulaId: 'past-simple',
    kind: 'standard',
    active: 'The CEO announced the merger at the press conference.',
    passive: 'The merger was announced by the CEO at the press conference.',
    vietnamese: 'Vụ sáp nhập đã được tổng giám đốc công bố tại buổi họp báo.',
    reversible: true,
    note: null,
  },
  {
    id: 'they-interviewed-candidates',
    formulaId: 'past-simple',
    kind: 'byOmitted',
    active: 'They interviewed twelve candidates last week.',
    passive: 'Twelve candidates were interviewed last week.',
    vietnamese: 'Mười hai ứng viên đã được phỏng vấn tuần trước.',
    reversible: false,
    note: NOTE_BY_OMITTED,
  },
  {
    id: 'someone-left-package',
    formulaId: 'past-simple',
    kind: 'byOmitted',
    active: 'Someone left this package at the reception desk.',
    passive: 'This package was left at the reception desk.',
    vietnamese: 'Kiện hàng này đã được để lại ở quầy lễ tân.',
    reversible: false,
    note: NOTE_BY_OMITTED,
  },

  // ── Quá khứ tiếp diễn ────────────────────────────────────────────────────
  {
    id: 'inspectors-checking-machines',
    formulaId: 'past-continuous',
    kind: 'standard',
    active: 'The inspectors were checking the machines all morning.',
    passive: 'The machines were being checked by the inspectors all morning.',
    vietnamese: 'Các máy móc đang được thanh tra viên kiểm tra suốt buổi sáng.',
    reversible: true,
    note: null,
  },
  {
    id: 'clerk-preparing-documents',
    formulaId: 'past-continuous',
    kind: 'standard',
    active: 'The clerk was preparing the documents at that time.',
    passive: 'The documents were being prepared by the clerk at that time.',
    vietnamese: 'Các giấy tờ đang được nhân viên văn thư chuẩn bị vào lúc đó.',
    reversible: true,
    note: null,
  },
  {
    id: 'staff-serving-guests',
    formulaId: 'past-continuous',
    kind: 'standard',
    active: 'Our staff were serving the guests when the power went out.',
    passive: 'The guests were being served by our staff when the power went out.',
    vietnamese: 'Khách đang được nhân viên của chúng tôi phục vụ thì mất điện.',
    reversible: true,
    note: null,
  },
  {
    id: 'they-renovating-third-floor',
    formulaId: 'past-continuous',
    kind: 'byOmitted',
    active: 'They were renovating the third floor when I visited.',
    passive: 'The third floor was being renovated when I visited.',
    vietnamese: 'Tầng ba đang được cải tạo khi tôi tới thăm.',
    reversible: false,
    note: NOTE_BY_OMITTED,
  },

  // ── Quá khứ hoàn thành ───────────────────────────────────────────────────
  {
    id: 'assistant-booked-conference-room',
    formulaId: 'past-perfect',
    kind: 'standard',
    active: 'The assistant had booked the conference room before the meeting.',
    passive: 'The conference room had been booked by the assistant before the meeting.',
    vietnamese: 'Phòng họp đã được trợ lý đặt trước khi cuộc họp diễn ra.',
    reversible: true,
    note: null,
  },
  {
    id: 'courier-delivered-samples',
    formulaId: 'past-perfect',
    kind: 'standard',
    active: 'The courier had delivered the samples before noon.',
    passive: 'The samples had been delivered by the courier before noon.',
    vietnamese: 'Các mẫu hàng đã được nhân viên chuyển phát giao trước buổi trưa.',
    reversible: true,
    note: null,
  },
  {
    id: 'previous-owner-sold-building',
    formulaId: 'past-perfect',
    kind: 'standard',
    active: 'The previous owner had sold the building by 2020.',
    passive: 'The building had been sold by the previous owner by 2020.',
    vietnamese: 'Toà nhà đã được chủ cũ bán trước năm 2020.',
    reversible: true,
    note: {
      vi: 'Câu này có hai chữ "by" khác nhau: "by the previous owner" chỉ người, còn "by 2020" chỉ mốc thời gian.',
      en: 'Two different "by" phrases here: "by the previous owner" is the agent, "by 2020" is a deadline.',
    },
  },
  {
    id: 'they-rejected-proposal',
    formulaId: 'past-perfect',
    kind: 'byOmitted',
    active: 'They had rejected the proposal before we arrived.',
    passive: 'The proposal had been rejected before we arrived.',
    vietnamese: 'Đề xuất đã bị bác bỏ trước khi chúng tôi tới.',
    reversible: false,
    note: NOTE_BY_OMITTED,
  },

  // ── Tương lai đơn ────────────────────────────────────────────────────────
  {
    id: 'committee-announce-results',
    formulaId: 'future-simple',
    kind: 'standard',
    active: 'The committee will announce the results on Friday.',
    passive: 'The results will be announced by the committee on Friday.',
    vietnamese: 'Kết quả sẽ được hội đồng công bố vào thứ Sáu.',
    reversible: true,
    note: null,
  },
  {
    id: 'team-handle-complaints',
    formulaId: 'future-simple',
    kind: 'standard',
    active: 'Our team will handle all customer complaints.',
    passive: 'All customer complaints will be handled by our team.',
    vietnamese: 'Mọi khiếu nại của khách hàng sẽ do nhóm chúng tôi xử lý.',
    reversible: true,
    note: null,
  },
  {
    id: 'airline-refund-ticket',
    formulaId: 'future-simple',
    kind: 'standard',
    active: 'The airline will refund the ticket price.',
    passive: 'The ticket price will be refunded by the airline.',
    vietnamese: 'Tiền vé sẽ được hãng hàng không hoàn lại.',
    reversible: true,
    note: null,
  },
  {
    id: 'architect-design-headquarters',
    formulaId: 'future-simple',
    kind: 'standard',
    active: 'A famous architect will design the new headquarters.',
    passive: 'The new headquarters will be designed by a famous architect.',
    vietnamese: 'Trụ sở mới sẽ được một kiến trúc sư nổi tiếng thiết kế.',
    reversible: true,
    note: null,
  },
  {
    id: 'they-install-software',
    formulaId: 'future-simple',
    kind: 'byOmitted',
    active: 'They will install the new software next month.',
    passive: 'The new software will be installed next month.',
    vietnamese: 'Phần mềm mới sẽ được cài đặt vào tháng tới.',
    reversible: false,
    note: NOTE_BY_OMITTED,
  },

  // ── Tương lai hoàn thành ─────────────────────────────────────────────────
  {
    id: 'auditors-complete-review',
    formulaId: 'future-perfect',
    kind: 'standard',
    active: 'The auditors will have completed the review by June.',
    passive: 'The review will have been completed by the auditors by June.',
    vietnamese: 'Cuộc rà soát sẽ được các kiểm toán viên hoàn tất trước tháng Sáu.',
    reversible: true,
    note: null,
  },
  {
    id: 'crew-clean-every-room',
    formulaId: 'future-perfect',
    kind: 'standard',
    active: 'The crew will have cleaned every room by ten o’clock.',
    passive: 'Every room will have been cleaned by the crew by ten o’clock.',
    vietnamese: 'Mọi phòng sẽ được đội dọn phòng làm sạch trước mười giờ.',
    reversible: true,
    note: null,
  },
  {
    id: 'they-ship-all-orders',
    formulaId: 'future-perfect',
    kind: 'byOmitted',
    active: 'They will have shipped all the orders by Friday.',
    passive: 'All the orders will have been shipped by Friday.',
    vietnamese: 'Toàn bộ đơn hàng sẽ được giao đi trước thứ Sáu.',
    reversible: false,
    note: NOTE_BY_OMITTED,
  },

  // ── Dự định (be going to) ────────────────────────────────────────────────
  {
    id: 'finance-team-review-budget',
    formulaId: 'be-going-to',
    kind: 'standard',
    active: 'The finance team is going to review the budget next quarter.',
    passive: 'The budget is going to be reviewed by the finance team next quarter.',
    vietnamese: 'Ngân sách sẽ được bộ phận tài chính rà soát trong quý tới.',
    reversible: true,
    note: null,
  },
  {
    id: 'company-launch-product-line',
    formulaId: 'be-going-to',
    kind: 'standard',
    active: 'The company is going to launch a new product line.',
    passive: 'A new product line is going to be launched by the company.',
    vietnamese: 'Một dòng sản phẩm mới sẽ được công ty ra mắt.',
    reversible: true,
    note: null,
  },
  {
    id: 'they-close-branch',
    formulaId: 'be-going-to',
    kind: 'byOmitted',
    active: 'They are going to close the branch in March.',
    passive: 'The branch is going to be closed in March.',
    vietnamese: 'Chi nhánh sẽ bị đóng cửa vào tháng Ba.',
    reversible: false,
    note: NOTE_BY_OMITTED,
  },

  // ── Động từ khuyết thiếu ─────────────────────────────────────────────────
  {
    id: 'anyone-can-use-printer',
    formulaId: 'modal',
    kind: 'modal',
    active: 'Anyone can use this printer.',
    passive: 'This printer can be used by anyone.',
    vietnamese: 'Chiếc máy in này ai cũng có thể dùng.',
    reversible: true,
    note: {
      vi: 'Sau động từ khuyết thiếu luôn là "be + V3", không chia gì thêm: can be used, must be done, should be sent.',
      en: 'After a modal it is always "be + V3", with no further changes: can be used, must be done, should be sent.',
    },
  },
  {
    id: 'technician-may-fix-fault',
    formulaId: 'modal',
    kind: 'modal',
    active: 'The technician may fix the fault today.',
    passive: 'The fault may be fixed by the technician today.',
    vietnamese: 'Sự cố có thể được kỹ thuật viên khắc phục ngay hôm nay.',
    reversible: true,
    note: null,
  },
  {
    id: 'you-must-submit-form',
    formulaId: 'modal',
    kind: 'modal',
    active: 'You must submit the form before Friday.',
    passive: 'The form must be submitted before Friday.',
    vietnamese: 'Đơn phải được nộp trước thứ Sáu.',
    reversible: false,
    note: {
      vi: 'Chủ ngữ "you" chỉ người nói đang nhắc chung chung, nên câu bị động bỏ hẳn "by you" — đây là kiểu câu của mọi bảng nội quy.',
      en: 'The "you" here is generic, so the passive drops "by you" entirely — this is how rules and notices are written.',
    },
  },
  {
    id: 'employees-should-report-accident',
    formulaId: 'modal',
    kind: 'modal',
    active: 'Employees should report any accident immediately.',
    passive: 'Any accident should be reported immediately.',
    vietnamese: 'Mọi tai nạn nên được báo cáo ngay lập tức.',
    reversible: false,
    note: null,
  },
  {
    id: 'we-can-deliver-goods',
    formulaId: 'modal',
    kind: 'modal',
    active: 'We can deliver the goods within two days.',
    passive: 'The goods can be delivered within two days.',
    vietnamese: 'Hàng có thể được giao trong vòng hai ngày.',
    reversible: false,
    note: null,
  },
  {
    id: 'visitors-must-wear-badge',
    formulaId: 'modal',
    kind: 'modal',
    active: 'Visitors must wear a badge at all times.',
    passive: 'A badge must be worn at all times.',
    vietnamese: 'Khách phải đeo thẻ mọi lúc.',
    reversible: false,
    note: null,
  },
  {
    id: 'you-should-not-leave-equipment',
    formulaId: 'modal',
    kind: 'modal',
    active: 'You should not leave the equipment unattended.',
    passive: 'The equipment should not be left unattended.',
    vietnamese: 'Không nên để thiết bị mà không có người trông.',
    reversible: false,
    note: {
      vi: 'Câu phủ định: "not" đứng ngay sau động từ khuyết thiếu, trước "be" — should not be left.',
      en: 'In the negative, "not" stays right after the modal and before "be" — should not be left.',
    },
  },

  // ── Hai tân ngữ ──────────────────────────────────────────────────────────
  {
    id: 'company-gave-employees-bonus',
    formulaId: 'past-simple',
    kind: 'twoObjects',
    active: 'The company gave the employees a bonus.',
    passive: 'The employees were given a bonus by the company.',
    vietnamese: 'Nhân viên đã được công ty thưởng.',
    reversible: true,
    note: NOTE_TWO_OBJECTS,
  },
  {
    id: 'bank-sends-us-statement',
    formulaId: 'present-simple',
    kind: 'twoObjects',
    active: 'The bank sends us a statement every month.',
    passive: 'We are sent a statement every month by the bank.',
    vietnamese: 'Chúng tôi được ngân hàng gửi sao kê hằng tháng.',
    reversible: true,
    note: NOTE_TWO_OBJECTS,
  },
  {
    id: 'manager-shown-interns-factory',
    formulaId: 'present-perfect',
    kind: 'twoObjects',
    active: 'The manager has shown the new interns the factory.',
    passive: 'The new interns have been shown the factory by the manager.',
    vietnamese: 'Các thực tập sinh mới đã được giám đốc dẫn đi tham quan nhà máy.',
    reversible: true,
    note: null,
  },
  {
    id: 'organisers-award-winner-trophy',
    formulaId: 'future-simple',
    kind: 'twoObjects',
    active: 'The organisers will award the winner a trophy.',
    passive: 'The winner will be awarded a trophy by the organisers.',
    vietnamese: 'Người thắng cuộc sẽ được ban tổ chức trao cúp.',
    reversible: true,
    note: null,
  },
  {
    id: 'they-offered-her-position',
    formulaId: 'past-simple',
    kind: 'twoObjects',
    active: 'They offered her the position of team leader.',
    passive: 'She was offered the position of team leader.',
    vietnamese: 'Cô ấy đã được mời giữ vị trí trưởng nhóm.',
    reversible: false,
    note: {
      vi: 'Tân ngữ "her" lên làm chủ ngữ thì phải đổi thành đại từ chủ ngữ "she" — đây là lỗi hay gặp nhất ở dạng hai tân ngữ.',
      en: 'When the object "her" becomes the subject it must change to the subject pronoun "she" — the most common slip in this pattern.',
    },
  },

  // ── Cụm động từ ──────────────────────────────────────────────────────────
  {
    id: 'committee-put-off-meeting',
    formulaId: 'past-simple',
    kind: 'phrasal',
    active: 'The committee put off the meeting until Monday.',
    passive: 'The meeting was put off by the committee until Monday.',
    vietnamese: 'Cuộc họp đã bị hội đồng hoãn tới thứ Hai.',
    reversible: true,
    note: NOTE_PHRASAL,
  },
  {
    id: 'staff-setting-up-exhibition',
    formulaId: 'present-continuous',
    kind: 'phrasal',
    active: 'The staff are setting up the exhibition hall.',
    passive: 'The exhibition hall is being set up by the staff.',
    vietnamese: 'Hội trường triển lãm đang được nhân viên chuẩn bị.',
    reversible: true,
    note: NOTE_PHRASAL,
  },
  {
    id: 'someone-must-look-into-complaint',
    formulaId: 'modal',
    kind: 'phrasal',
    active: 'Someone must look into this complaint.',
    passive: 'This complaint must be looked into.',
    vietnamese: 'Khiếu nại này phải được xem xét.',
    reversible: false,
    note: {
      vi: 'Cụm "look into" giữ nguyên giới từ dù đứng ở cuối câu: "must be looked into", không phải "must be looked".',
      en: 'The particle in "look into" stays even at the end of the sentence: "must be looked into", not "must be looked".',
    },
  },
  {
    id: 'they-called-off-launch',
    formulaId: 'present-perfect',
    kind: 'phrasal',
    active: 'They have called off the product launch.',
    passive: 'The product launch has been called off.',
    vietnamese: 'Buổi ra mắt sản phẩm đã bị huỷ.',
    reversible: false,
    note: NOTE_PHRASAL,
  },
  {
    id: 'we-carry-out-survey',
    formulaId: 'future-simple',
    kind: 'phrasal',
    active: 'We will carry out the survey in June.',
    passive: 'The survey will be carried out in June.',
    vietnamese: 'Cuộc khảo sát sẽ được tiến hành vào tháng Sáu.',
    reversible: false,
    note: NOTE_PHRASAL,
  },
];
